-- =====================================================
-- Enterprise Retail Data Warehouse
-- File: 02_intermediate_queries.sql
-- Description:
-- Intermediate SQL queries for business reporting using
-- GROUP BY, HAVING, JOINs, CASE, and Date Functions.
-- =====================================================

SET search_path TO retailhub;

-- =====================================================
-- Sales Performance
-- =====================================================

-- 1. Total revenue generated by each store
SELECT
    s.store_name,
    ROUND(SUM(p.amount), 2) AS total_revenue
FROM payments p
JOIN orders o ON p.order_id = o.order_id
JOIN stores s ON o.store_id = s.store_id
WHERE p.payment_status = 'Completed'
GROUP BY s.store_name
ORDER BY total_revenue DESC;

-- 2. Number of orders handled by each store
SELECT
    s.store_name,
    COUNT(o.order_id) AS total_orders
FROM stores s
JOIN orders o ON s.store_id = o.store_id
GROUP BY s.store_name
ORDER BY total_orders DESC;

-- 3. Revenue generated through each sales channel
SELECT
    o.sales_channel,
    ROUND(SUM(p.amount),2) AS revenue
FROM orders o
JOIN payments p ON o.order_id = p.order_id
WHERE p.payment_status = 'Completed'
GROUP BY o.sales_channel
ORDER BY revenue DESC;

-- 4. Monthly revenue report
SELECT
    DATE_TRUNC('month', payment_date) AS month,
    ROUND(SUM(amount),2) AS revenue
FROM payments
WHERE payment_status = 'Completed'
GROUP BY DATE_TRUNC('month', payment_date)
ORDER BY month;

-- 5. Average order value by sales channel
SELECT
    o.sales_channel,
    ROUND(AVG(p.amount),2) AS average_order_value
FROM orders o
JOIN payments p ON o.order_id = p.order_id
WHERE p.payment_status='Completed'
GROUP BY o.sales_channel;

-- =====================================================
-- Customer Analysis
-- =====================================================

-- 6. Number of customers by membership level
SELECT
    membership_level,
    COUNT(*) AS customer_count
FROM customers
GROUP BY membership_level
ORDER BY customer_count DESC;

-- 7. Customers from each state
SELECT
    state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY state
ORDER BY total_customers DESC;

-- 8. Customers with more than 5 orders
SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
GROUP BY c.customer_id,c.first_name,c.last_name
HAVING COUNT(o.order_id)>5
ORDER BY total_orders DESC;

-- 9. Average spending by membership level
SELECT
    c.membership_level,
    ROUND(AVG(p.amount),2) AS average_spending
FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
JOIN payments p ON o.order_id=p.order_id
WHERE p.payment_status='Completed'
GROUP BY c.membership_level;

-- 10. Customer registrations by year
SELECT
    EXTRACT(YEAR FROM registration_date) AS registration_year,
    COUNT(*) AS total_customers
FROM customers
GROUP BY registration_year
ORDER BY registration_year;

-- =====================================================
-- Product Analysis
-- =====================================================

-- 11. Number of products in each category
SELECT
    c.category_name,
    COUNT(*) AS total_products
FROM products p
JOIN categories c
ON p.category_id=c.category_id
GROUP BY c.category_name
ORDER BY total_products DESC;

-- 12. Average selling price by category
SELECT
    c.category_name,
    ROUND(AVG(p.selling_price),2) AS average_price
FROM products p
JOIN categories c
ON p.category_id=c.category_id
GROUP BY c.category_name
ORDER BY average_price DESC;

-- 13. Products launched each year
SELECT
    EXTRACT(YEAR FROM launch_date) AS launch_year,
    COUNT(*) AS total_products
FROM products
GROUP BY launch_year
ORDER BY launch_year;

-- 14. Number of products by brand
SELECT
    b.brand_name,
    COUNT(*) AS total_products
FROM products p
JOIN brands b
ON p.brand_id=b.brand_id
GROUP BY b.brand_name
ORDER BY total_products DESC;

-- 15. Categories with more than 20 products
SELECT
    c.category_name,
    COUNT(*) AS total_products
FROM products p
JOIN categories c
ON p.category_id=c.category_id
GROUP BY c.category_name
HAVING COUNT(*)>20
ORDER BY total_products DESC;

-- =====================================================
-- Inventory Analysis
-- =====================================================

-- 16. Total stock available in each warehouse
SELECT
    w.warehouse_name,
    SUM(i.stock_quantity) AS total_stock
FROM inventory i
JOIN warehouses w
ON i.warehouse_id=w.warehouse_id
GROUP BY w.warehouse_name
ORDER BY total_stock DESC;

-- 17. Products that need restocking
SELECT
    p.product_name,
    w.warehouse_name,
    i.stock_quantity,
    i.reorder_level
FROM inventory i
JOIN products p
ON i.product_id=p.product_id
JOIN warehouses w
ON i.warehouse_id=w.warehouse_id
WHERE i.stock_quantity<=i.reorder_level;

-- =====================================================
-- Payment Analysis
-- =====================================================

-- 18. Payments by payment method
SELECT
    payment_method,
    COUNT(*) AS total_transactions,
    ROUND(SUM(amount),2) AS total_amount
FROM payments
GROUP BY payment_method
ORDER BY total_amount DESC;

-- 19. Payment status summary
SELECT
    payment_status,
    COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_status;

-- =====================================================
-- Shipment Analysis
-- =====================================================

-- 20. Shipments by delivery status
SELECT
    delivery_status,
    COUNT(*) AS total_shipments
FROM shipments
GROUP BY delivery_status;

-- 21. Average shipping cost by carrier
SELECT
    carrier,
    ROUND(AVG(shipping_cost),2) AS average_shipping_cost
FROM shipments
GROUP BY carrier
ORDER BY average_shipping_cost DESC;

-- =====================================================
-- CASE Statements
-- =====================================================

-- 22. Product price category
SELECT
    product_name,
    selling_price,
    CASE
        WHEN selling_price < 500 THEN 'Budget'
        WHEN selling_price BETWEEN 500 AND 2000 THEN 'Mid Range'
        ELSE 'Premium'
    END AS price_category
FROM products;

-- 23. Inventory stock status
SELECT
    product_id,
    stock_quantity,
    reorder_level,
    CASE
        WHEN stock_quantity <= reorder_level THEN 'Restock Required'
        ELSE 'Stock Available'
    END AS stock_status
FROM inventory;

-- 24. Customer category based on total spending
SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    SUM(p.amount) AS total_spent,
    CASE
        WHEN SUM(p.amount) >= 50000 THEN 'VIP'
        WHEN SUM(p.amount) >= 20000 THEN 'Premium'
        ELSE 'Regular'
    END AS customer_segment
FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
JOIN payments p ON o.order_id=p.order_id
WHERE p.payment_status='Completed'
GROUP BY c.customer_id,c.first_name,c.last_name
ORDER BY total_spent DESC;

-- 25. Store performance classification
SELECT
    s.store_name,
    ROUND(SUM(p.amount),2) AS revenue,
    CASE
        WHEN SUM(p.amount) >= 1000000 THEN 'Excellent'
        WHEN SUM(p.amount) >= 500000 THEN 'Good'
        ELSE 'Needs Improvement'
    END AS performance
FROM stores s
JOIN orders o ON s.store_id=o.store_id
JOIN payments p ON o.order_id=p.order_id
WHERE p.payment_status='Completed'
GROUP BY s.store_name
ORDER BY revenue DESC;